task_type: detection
dataset_category: coco
calibration_dataset:
  num_classes: null
  num_frames: 400
  name: modelmaker
  path: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/dataset
  split: train
  shuffle: true
  dataset_info: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/dataset.yaml
input_dataset:
  num_classes: null
  num_frames: 418
  name: modelmaker
  path: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/dataset
  split: val
  shuffle: false
  dataset_info: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/dataset.yaml
preprocess:
  resize: 640
  crop: 640
  data_layout: NCHW
  reverse_channels: true
  backend: cv2
  interpolation: null
  add_flip_image: false
  resize_with_pad:
  - true
  - corner
  pad_color:
  - 114
  - 114
  - 114
session:
  session_name: onnxrt
  work_dir: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work
  target_machine: pc
  target_device: AM62A
  run_suffix: null
  tidl_offload: true
  input_optimization: false
  input_data_layout: NCHW
  input_mean:
  - 0.0
  - 0.0
  - 0.0
  input_scale:
  - 1.0
  - 1.0
  - 1.0
  run_dir_tree_depth: 3
  runtime_options:
    platform: J7
    version: 10.0.2
    tidl_tools_path: ../edgeai-benchmark/tools/AM62A/tidl_tools
    artifacts_folder: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/artifacts
    tensor_bits: 16
    import: 'yes'
    accuracy_level: 1
    debug_level: 0
    inference_mode: 0
    advanced_options:high_resolution_optimization: 0
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:calibration_frames: 200
    advanced_options:calibration_iterations: 50
    advanced_options:quantization_scale_type: 4
    advanced_options:activation_clipping: 1
    advanced_options:weight_clipping: 1
    advanced_options:bias_calibration: 1
    advanced_options:output_feature_16bit_names_list: /multi_level_conv_obj.2/Conv_output_0,
      /multi_level_conv_reg.2/Conv_output_0, /multi_level_conv_cls.2/Conv_output_0,
      /multi_level_conv_obj.1/Conv_output_0, /multi_level_conv_reg.1/Conv_output_0,
      /multi_level_conv_cls.1/Conv_output_0, /multi_level_conv_obj.0/Conv_output_0,
      /multi_level_conv_reg.0/Conv_output_0, /multi_level_conv_cls.0/Conv_output_0
    advanced_options:params_16bit_names_list: ''
    advanced_options:add_data_convert_ops: 3
    ti_internal_nc_flag: 83886080
    info:
      prequantized_model_type: null
    object_detection:confidence_threshold: 0.1
    object_detection:top_k: 500
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/model/model.prototxt
    advanced_options:quant_params_proto_path: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/model/model_qparams.prototxt
  model_path: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/training/model.onnx
  tidl_tools_path: ../edgeai-benchmark/tools/AM62A/tidl_tools
  run_dir: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220
  num_tidl_subgraphs: 16
  model_id: od-8220
  model_type: null
  input_details:
  - name: input
    shape:
    - 1
    - 3
    - 640
    - 640
    type: tensor(float)
  output_details:
  - name: dets
    shape:
    - 1
    - 1
    - 1
    - 1
    - 200
    - 5
    type: tensor(float)
  - name: labels
    shape:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 200
    type: tensor(int64)
  num_inputs: 1
  extra_inputs: null
  tensor_bits: 8
  quant_params_proto_path: true
  supported_machines: null
  with_onnxsim: false
  shape_inference: true
  tidl_onnx_model_optimizer: null
  deny_list_from_start_end_node: null
  output_feature_16bit_names_list_from_start_end: null
  artifacts_folder: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/artifacts
  model_folder: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/model
  model_file: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/model/model.onnx
postprocess:
  detection_threshold: 0.1
  save_output: true
  formatter:
    src_indices:
    - 5
    - 4
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
  resize_with_pad: true
  normalized_detections: false
  shuffle_indices: null
  squeeze_axis: null
  ignore_index: null
  logits_bbox_to_bbox_ls: false
metric:
  label_offset_pred: 1
model_info:
  metric_reference:
    accuracy_ap[.5:.95]%: null
  model_shortlist: 10
  compact_name: yolox-s-lite-mmdet-coco-640x640
  shortlisted: true
  recommended: true
