calibration_dataset:
  dataset_info: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/dataset.yaml
  name: modelmaker
  num_classes: null
  num_frames: 400
  path: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/dataset
  shuffle: true
  split: train
dataset_category: coco
input_dataset:
  dataset_info: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/dataset.yaml
  name: modelmaker
  num_classes: null
  num_frames: 418
  path: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/dataset
  shuffle: false
  split: val
metric:
  label_offset_pred: 1
  run_dir: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220
model_info:
  compact_name: yolox-s-lite-mmdet-coco-640x640
  metric_reference:
    accuracy_ap[.5:.95]%: null
  model_shortlist: 10
  recommended: true
  shortlisted: true
postprocess:
  detection_threshold: 0.1
  formatter:
    dst_indices:
    - 4
    - 5
    name: DetectionBoxSL2BoxLS
    src_indices:
    - 5
    - 4
  ignore_index: null
  logits_bbox_to_bbox_ls: false
  normalized_detections: false
  resize_with_pad: true
  save_output: true
  shuffle_indices: null
  squeeze_axis: null
preprocess:
  add_flip_image: false
  backend: cv2
  crop: 640
  data_layout: NCHW
  interpolation: null
  pad_color:
  - 114
  - 114
  - 114
  resize: 640
  resize_with_pad:
  - true
  - corner
  reverse_channels: true
session:
  artifacts_folder: artifacts
  deny_list_from_start_end_node: null
  extra_inputs: null
  input_data_layout: NCHW
  input_details:
  - name: input
    shape:
    - 1
    - 3
    - 640
    - 640
    type: tensor(float)
  input_mean:
  - 0.0
  - 0.0
  - 0.0
  input_optimization: false
  input_scale:
  - 1.0
  - 1.0
  - 1.0
  model_file: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/model/model.onnx
  model_folder: model
  model_id: od-8220
  model_path: model/model.onnx
  model_type: null
  num_inputs: 1
  num_tidl_subgraphs: 16
  output_details:
  - name: dets
    shape:
    - 1
    - 1
    - 1
    - 1
    - 200
    - 5
    type: tensor(float)
  - name: labels
    shape:
    - 1
    - 1
    - 1
    - 1
    - 1
    - 200
    type: tensor(int64)
  output_feature_16bit_names_list_from_start_end: null
  quant_params_proto_path: true
  run_dir: od-8220
  run_dir_tree_depth: 3
  run_suffix: null
  runtime_options:
    accuracy_level: 1
    advanced_options:activation_clipping: 1
    advanced_options:add_data_convert_ops: 3
    advanced_options:bias_calibration: 1
    advanced_options:calibration_frames: 200
    advanced_options:calibration_iterations: 50
    advanced_options:high_resolution_optimization: 0
    advanced_options:output_feature_16bit_names_list: /multi_level_conv_obj.2/Conv_output_0,
      /multi_level_conv_reg.2/Conv_output_0, /multi_level_conv_cls.2/Conv_output_0,
      /multi_level_conv_obj.1/Conv_output_0, /multi_level_conv_reg.1/Conv_output_0,
      /multi_level_conv_cls.1/Conv_output_0, /multi_level_conv_obj.0/Conv_output_0,
      /multi_level_conv_reg.0/Conv_output_0, /multi_level_conv_cls.0/Conv_output_0
    advanced_options:params_16bit_names_list: ''
    advanced_options:pre_batchnorm_fold: 1
    advanced_options:quant_params_proto_path: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/model/model_qparams.prototxt
    advanced_options:quantization_scale_type: 4
    advanced_options:weight_clipping: 1
    artifacts_folder: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/artifacts
    debug_level: 0
    import: 'no'
    inference_mode: 0
    info:
      prequantized_model_type: null
    object_detection:confidence_threshold: 0.1
    object_detection:meta_arch_type: 6
    object_detection:meta_layers_names_list: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work/od-8220/model/model.prototxt
    object_detection:top_k: 500
    platform: J7
    tensor_bits: 16
    ti_internal_nc_flag: 83886080
    tidl_tools_path: ../edgeai-benchmark/tools/AM62A/tidl_tools
    version: 10.0.2
  session_name: onnxrt
  shape_inference: true
  supported_machines: null
  target_device: AM62A
  target_machine: pc
  tensor_bits: 8
  tidl_offload: true
  tidl_onnx_model_optimizer: null
  tidl_tools_path: ../edgeai-benchmark/tools/AM62A/tidl_tools
  with_onnxsim: false
  work_dir: /local_data/home/mattmak/mattmak_20250314/edgeai-tensorlab/edgeai-modelmaker/data/projects/htt_Fan_Matt_basic_cam.v8i.coco_RAW/run/20250422-125939/yolox_s_lite/compilation/AM62A/work
task_type: detection
